name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/money:latest

      - name: Run container to check if the application starts
        run: |
          docker run --rm -d --name test_container -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/money:latest
          sleep 10  # Wait a bit to ensure the application has time to start
          if ! docker ps | grep test_container; then
            echo "Application failed to start"
            docker logs test_container
            docker stop test_container
            exit 1
          fi
          docker stop test_container

      - name: Push Docker image
        if: success()  # Only push if previous steps were successful
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/money:latest
